### PR TITLE
:chains: Module 1: Added 3 files (HTML, CSS, MD)

### PR DESCRIPTION
**Pull request by mahabubx7**
:heavy_check_mark: Added .html file with `h1` tag and message
:heavy_check_mark: Added .css file with `h1` tag style for color
:heavy_check_mark: Added test.md file with the message and ignored by `.gitignore`

### CODE REVIEW

**Review by ichala — CHANGES_REQUESTED** [review]
Hi @mahabubx7 
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- .gitignore created  ✔️ 
- Correct Readme Template ✔️ 


 ## Required Changes ♻️

- [x] **_🛑 as part of the requirements you need to set up the [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) Linters, kindly follow this [guide ](https://github.com/microverseinc/linters-config/tree/master/html-css) to learn how to set them up in your repo 🙏_**


## Optional suggestions

- in your future projects kindly make sure to use descriptive commit messages - each commit should be small enough to describe it in one sentence. The commit message should be written _**in the imperative tense and capitalized**_. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8).

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mahabubx7** [comment]
hi, @ichala
I have committed my lint configs now :heavy_check_mark: 
Please check :blush:

**Comment by ichala** [comment]
> hi, @ichala I have committed my lint configs now ✔️ Please check 😊

you still didn't install the linters , kindly set them up & then request another review from your dashboard

**Comment by mahabubx7** [comment]
image

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @mahabubx7, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - Professional README. ✔️
 - Correct Github flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [x] I see that you installed the linters locally, but in order to the linters checks run on the Pull Request, the `linters.yml` file in the `.github/workflows/` folder should be added to the project. Please add this file in the correct repository I mentioned so the [linters](https://github.com/microverseinc/linters-config) can run on this PR and help the code review flow.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mahabubx7** [comment]
hi @leonardodiasb :hand: 
Now I got it and already pushed my changes.

**Review by divinecharlotte — APPROVED** [review]
Hi @mahabubx7 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
